---
# tasks file for mysqlrole
- name: install mysql
  yum: name=mariadb105-server state=present

- name: start mysql
  service: name=mariadb state=started

  notify: restart httpd
  notify: restart php8.1-fpm
  notify: restart mariadb
